### ISSUE TITLE
pgeof as a pip package

### ISSUE THREAD

**Issue by drprojects** [drprojects/point_geometric_features#11]
Packaging `pgeof` as a pip package, free from the conda dependency of `eigen3` would be great.

@rjanvier I think you were thinking of working on this at some point. Is this still something you are considering ?

**Comment by rjanvier** [comment]
yep, "new" pgeof use Eigen as submodule, to come this week

**Comment by rjanvier** [comment]
it's already packaged for PyPI here https://pypi.org/project/pgeof/ `pip install pgeof` just do the trick.

**Comment by drprojects** [comment]
> yep, "new" pgeof use Eigen as submodule, to come this week

Oh cool ! So, to be sure I understand correctly: you intend to release pre-compiled binaries for `pegeof` which can be installed  with`pip install pgeof` without the need for explicitly installing `eigen` before with, say:

```bash
conda install -c omnia eigen3
export EIGEN_LIB_PATH="path_to_eigen_root_dir"
``` ?

**Comment by rjanvier** [comment]
Maybe if you want to test the current package without risk, in your console try something like
`python -m venv testpgeof ` -> create a virtual env in the directory `testpgeof`
`source testpgeof/bin/activate` -> activate the virtual env (now you are isolated from other python distribution
`python -m pip install pgeof` -> install a precompiled wheel of pgeof from PyPI
`python -c "import pgeof;help(pgeof)"` -> should display pgeof help
`deactivate` -> deactivate your virtual env, come back to your current python distribution
rm your venv if needed

**Comment by drprojects** [comment]
Cool, thanks for the feedback. I will likely setup a DL machine from scratch in the coming days, will test it then !

**Comment by rjanvier** [comment]
@drprojects, 
I remember I put a placeholder in the copyright here https://github.com/drprojects/point_geometric_features/blob/main/LICENSE because it was the one from Ashleve. 
Maybe you could update the copyright with a proper attribution (Loic, you or your institution...). Thank in advance!

**Comment by drprojects** [comment]
Thanks for reminding me, I did not think of checking it. Just updated it and added you to it, since you have been actively pushing this project too !
