### ISSUE TITLE
Migrate from distutils to setuptools

### ISSUE THREAD

**Issue by rjanvier** [drprojects/point_geometric_features#4]
Hi Damien,

For a bit of context, I currently use @drprojects/superpoint_transformer to make some forest segmentation for the @3DFin project. It works pretty well but we want to lower the technical cost of using it (in an inference context) for scientist interested in the field of Forest management. 

I started to review compiled dependency and evaluate if we can offer pre build wheels (via https://github.com/pypa/cibuildwheel). I first noticed that all your C++ based python module/dependencies use `distutils` as a build system. `distutils` is deprecated and I think it did not even work anymore with `python 3.12`. So future users could have hard time to install your dependencies. Would you agree if I try to port `pgeof` to `setuptools `build system (which is the "drop in" replacement for `distutils`)?

**Comment by rjanvier** [comment]
Hi Damien,
Thanks a lot! 
For now I will focus on easing the installation of pgeof and cut pursuit. I have a  CloudCompare plugin for "SPT-Inference" in mind and I want to reduce python dependencies or the need of a c++ compiler to install them. I also plan to offer alternative to CUDA-only modules (FRNN could be replaced by scikit CKDTree / Nanoflann in a CPU only context). Multiscale features sound like a good idea, it reminds me https://inria.hal.science/hal-00713678v2/document somehow

**Comment by drprojects** [comment]
Hi Romain, 

Glad to hear you are also interested in [SPT](https://github.com/drprojects/superpoint_transformer) ! Same as above, I would love to wrap it as a simple `pip` package somehow but cannot dedicate time to this. 

So, I trust that your skills for simplifying the dependencies, I agree that would help the installation. 

Would you mind creating an issue on [SPT](https://github.com/drprojects/superpoint_transformer) for discussing SPT-specific stuff, when relevant ?

Regarding the multiscale features, you are right, I do not claim any novelty in this idea, it has a long history in literature. Just thought it would be an easy extension to `pgeof` and would be curious to see how it could help downstream models like SPT for instance (at the cost of some extra hyperparameters).

Thanks for your help

**Comment by loicland** [comment]
Hi @rjanvier 
I am one of the creators of cut pursuit. If you also need to port cut pursuit ([this repo](https://gitlab.com/1a7r0ch3/parallel-cut-pursuit)) to setuptools and need any help, do not hesitate.
